# .github/workflows/ci-cd.yml
name: Upload to pypi
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/consort-yaml
    permissions:
      id-token: write  
    steps:
    - uses: actions/checkout@v7
    - name: Install uv
      uses: astral-sh/setup-uv
    - name: Build package
      run: uv build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1